### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by bemoregt** [imatge-upc/detection-2016-nipsws#26]
Hi, @xavigiro @jorditorresBCN @miriambellver @skrish13 @verovilaplana 

I've met this error:

kerb:scripts mun$ 
kerb:scripts mun$ python3 image_zooms_training.py -n 0
Using TensorFlow backend.
Traceback (most recent call last):
  File "image_zooms_training.py", line 6, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python3.6/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python3.6/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
kerb:scripts mun$ 

What's wrong to me?

Thanks in advance.

from @bemoregt.

**Comment by skrish13** [comment]
tf version mismatches? tf has undergone lots of major changes since this code was written I'd beleive.

**Comment by bemoregt** [comment]
Hi, @skrish13 @xavigiro @jorditorresBCN @miriambellver @verovilaplana  

What is the compatible tf version ?

Thanks.

from @bemoregt
