### ISSUE TITLE
IOError: Unable to create file

### ISSUE THREAD

**Issue by NIEYALI** [imatge-upc/detection-2016-nipsws#5]
Dear  miriambellver , thanks for your share. I use theano0.9 and  keras=1.1.0 . But I met this problem:
Using Theano backend.
Using gpu device 0: GeForce GTX 1070 (CNMeM is enabled with initial size: 75.0% of memory, cuDNN 5105)
/home/sook/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
/home/sook/detection/scripts/parse_xml_annotations.py:51: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  masks[annotation[i, 3]:annotation[i, 4], annotation[i, 1]:annotation[i, 2], i] = 1
image_zooms_training.py:220: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  offset_aux[1]:offset_aux[1] + size_mask[1]]
image_zooms_training.py:221: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  region_mask[offset[0]:offset[0] + size_mask[0], offset[1]:offset[1] + size_mask[1]] = 1
Traceback (most recent call last):
  File "image_zooms_training.py", line 284, in <module>
    model.save_weights(string, overwrite=True)
  File "/home/sook/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2443, in save_weights
    f = h5py.File(filepath, 'w')
  File "/home/sook/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/sook/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 98, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "h5py/h5f.pyx", line 96, in h5py.h5f.create (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:2109)
IOError: Unable to create file (Unable to open file: name = '../models_image_zooms/model0_epoch_0h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)

could you tell me what happen ?
Thanks a lot

**Comment by miriambellver** [comment]
Hi! have you created the models_image_zooms folder, following the steps of the readme? maybe there is no folder and for this reason the model can't be saved

**Comment by NIEYALI** [comment]
Thanks a lot , miriambellver, it woks
